apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cliente-deploy.yaml
  - cliente-service.yaml
  - cliente-ingress.yaml
images:
  - name: cliente-service
    newName: guilhermesav/cliente-service
    newTag: "221214.aa59924"
