apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cliente-deploy.yml
  - cliente-service.yml
  - cliente-ingress.yml
images:
  - name: cliente-service
    newName: guilhermesav/cliente-service
    newTag: "221215.d1c80f9"
